<?php $brand = $this->getBrand();  ?>

<?php if ($brand): ?>

    <h3><?php echo $this->__('Brand'); ?></h3>
    <p><a href="<?php echo $this->helper('smashingmagazine_brandexample/brand')->getBrandUrl($brand); ?>" title="<?php echo $this->escapeHtml($brand->getName()); ?>">
            <img src="<?php echo Mage::getBaseUrl('media').'brand/'.$brand->getImage() ?>" width="100" /><?php echo $brand->getName(); ?></a></p>
    
<?php endif; ?>